version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    networks:
      - app-network

  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge